#!/usr/bin/env bash

SCRIPTPATH="$(cd "$(dirname "$0")" || exit && pwd -P)"

#set background
if [ -x "$(command -v feh)" ]; then
	feh --bg-scale "$SCRIPTPATH"/down.jpg
fi

leftwm-command "UnloadTheme"

# User script
source "$SCRIPTPATH"/user_down
