#!/usr/bin/env bash
SCRIPTPATH="$(cd "$(dirname "$0")" || exit && pwd -P)"
export SCRIPTPATH

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
	/tmp/leftwm-theme-down
	rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

#set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

#set background
if [ -x "$(command -v feh)" ]; then
	feh --bg-scale "$SCRIPTPATH"/background.jpg
fi

# Load user programs
source "$SCRIPTPATH"/user_up

# Start polybar
index=0
monitors="$(polybar -m | sed s/:.*//)"
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x _y; do
	((indextemp = index + 1))
	monitor=$(sed "$indextemp!d" <<<"$monitors")
	barname="mainbar$index"
	monitor=$monitor offset=$x width=$width polybar -c "$SCRIPTPATH"/polybar.config $barname &>/dev/null &
	((index = indextemp))
done
