#!/usr/bin/env bash

export SCRIPTPATH="$(cd "$(dirname "$0")" || exit && pwd -P)"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
        /tmp/leftwm-theme-down
        rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

#set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# Load user programs
source "$SCRIPTPATH"/user_up

# Start polybar
source "$SCRIPTPATH"/polybar_launcher.sh
