#!/usr/bin/bash

SCRIPTPATH="$(cd "$(dirname "$0")" || exit && pwd -P)"

# Pywal
# -R restores the last colorscheme that was in use.
# wal -R

# Restore wallpaper
feh --bg-fill "$SCRIPTPATH/wallpapers/119860.jpg"

# Start user programs
declare -a launch_programs=(

	# https://github.com/dccsillag/picom | git clone -b implement-window-animations https://github.com/dccsillag/picom.git | Animations branch
	"picom --animations --experimental-backend --config $SCRIPTPATH/configs/picom.conf"
	# "optimus-manager-qt"
	"unclutter"
	"greenclip daemon"
	"dunst -conf $SCRIPTPATH/configs/dunstrc"
	
)

for item in "${launch_programs[@]}"; do
	if ! pgrep -u $UID -f -x "$item" &>/dev/null; then
		$item &>/dev/null &
	fi
done
