#!/usr/bin/env bash
# The script won't run on soft reload

# End user programs
declare -a end_programs=(
"picom"
"unclutter"
"greenclip"
"dunst"
)

for item in "${end_programs[@]}"; do
        pkill "$item"
done
