#!/usr/bin/env bash
# Script won't run on soft reload

# End user programs
declare -a launch_programs=(
	"picom"
	"optimus-manager-qt"
	"unclutter"
	"greenclip daemon"
)

for item in "${launch_programs[@]}"; do
	pkill "$item"
done
