#!/usr/bin/env bash
# Script won't run on soft reload

# End user programs
declare -a end_programs=(
	"picom"
	"optimus-manager-qt"
	"unclutter"
	"greenclip"
	"dunst"
)

for item in "${end_programs[@]}"; do
	pkill "$item"
done
