#!/usr/bin/env bash

# Pywal
# -R restores the last colorscheme that was in use.
wal -R

# User programs
# Start compositor
picom --animations --experimental-backend --config "$SCRIPTPATH"/configs/picom.conf &
optimus-manager-qt &
unclutter &
