#!/usr/bin/env bash

timestamp="$(date +%d.%m.%Y"_"%H:%M:%S)"
targetbase="$HOME/Pictures/screenshots"
mkdir -p "${targetbase}"
[[ -d "${targetbase}" ]] || exit 1
scrot --silent --select --freeze "${targetbase}/${timestamp}.png"

sleep 1
dunstify --raw_icon="${targetbase}/${timestamp}.png" "Saved: " "Pictures/screenshots/${timestamp}.png"
